# Generated by Django 3.1.6 on 2021-02-25 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Middag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('guests', models.PositiveSmallIntegerField()),
                ('sharing', models.CharField(choices=[('ja', 'Ja'), ('no', 'Nei')], default='ja', max_length=2)),
                ('sharing_cost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allergener', multiselectfield.db.fields.MultiSelectField(choices=[('GLUTEN', 'Gluten'), ('LAKTOSE', 'Laktose'), ('EGG', 'Egg'), ('NØTTER', 'Nøtter'), ('INGEN', 'Ingen')], max_length=31)),
                ('address', models.CharField(default=None, max_length=200)),
                ('postnr', models.PositiveSmallIntegerField(default=None)),
                ('poststed', models.CharField(default=None, max_length=200)),
                ('date_of_dinner', models.DateTimeField(default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
