# Generated by Django 3.1.6 on 2021-02-23 23:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20210223_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middag',
            name='allergener',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GLUTEN', 'Gluten'), ('LAKTOSE', 'Laktose'), ('EGG', 'Egg'), ('NØTTER', 'Nøtter'), ('INGEN', 'Ingen')], max_length=31),
        ),
    ]
